### PR TITLE
bugfix: LeaderElectionID must be configured

### PR DESCRIPTION
**Pull request by lbbniu**
bugfix: https://github.com/AliyunContainerService/kubernetes-cronhpa-controller/issues/103

### CODE REVIEW

**Comment by lbbniu** [comment]
bugfix: https://github.com/AliyunContainerService/kubernetes-cronhpa-controller/issues/103

**Comment by vivek0464** [comment]
@lbbniu I ran this in our k8s cluster with 3 replicas for controller, logs show that one of the pod acquired the lock but suddenly pods start terminating and only single pod remains finally.

**Comment by lbbniu** [comment]
> 

which pod is left at the end？

**Comment by vivek0464** [comment]
One which acquired the lock, the first created one

**Comment by vivek0464** [comment]
I see an hpa named kubernetes-cronhpa-controller-generator-hpa gets autogenerated, and it is scaling down the replicas. 
```
│ Name:                                                  kubernetes-cronhpa-controller-generator-hpa                                                       │
│ Namespace:                                             test                                                                                               │
│ Labels:                                                owning_resource_name=kubernetes-cronhpa-controller                                                │
│                                                        owning_resource_p_servicegroup=                                                                   │
│                                                        owning_resource_p_servicename=                                                                    │
│ Annotations:                                           <none>                                                                                            │
│ CreationTimestamp:                                     Tue, 30 Aug 2022 21:20:30 +0530                                                                   │
│ Reference:                                             Deployment/kubernetes-cronhpa-controller                                                          │
│ Metrics:                                               ( current / target )                                                                              │
│   resource cpu on pods  (as a percentage of request):  <unknown> / 60%                                                                                   │
│ Min replicas:                                          1                                                                                                 │
│ Max replicas:                                          4                                                                                                 │
│ Deployment pods:                                       3 current / 0 desired

```

**Comment by vivek0464** [comment]
My bad, this is an issue with my environment. Thank you so much @lbbniu for looking into it :)

**Pull request merged**
