### PR TITLE
add serviceMonitor for prometheus-operater

### PR DESCRIPTION
**Pull request by yccharles**
kubernetes-cronhpa-controller auto discovery by prometheus-operater

### CODE REVIEW

**Comment by yccharles** [comment]
anyone here?

**Comment by ringtail** [comment]
@yccharles currently, we don't have much metrics.

**Comment by yccharles** [comment]
Each component in k8s need to be monitoring. 
Its forcus on  prometheus monitoring kubernetes-cronhpa-controller automatically.  Not related to the number of metric.
That's means users do not need config promethues by hand.

**Comment by ringtail** [comment]
> Each component in k8s need to be monitoring. Its forcus on prometheus monitoring kubernetes-cronhpa-controller automatically. Not related to the number of metric. That's means users do not need config promethues by hand.

I agree.

**Pull request merged**
