### PR TITLE
feat(chart): config cleanup job image

### PR DESCRIPTION
**Pull request by EnnnOK**
# Why this
I want to config cleanup job image with values.yaml

### CODE REVIEW

**Comment by EnnnOK** [comment]
@ringtail

**Comment by ringtail** [comment]
@EnnnOK I am not sure about that. But I think it should be an optional choose for users.

**Comment by EnnnOK** [comment]
> that

Yes. If user use private docker registry, they must modify chart files when they want to remove CRDs because their environment can not get cleanup image. If we config cleanup image in values.yaml,  they don't need to modify chart,  just pass helm config parameter.

**Pull request merged**
